### ISSUE TITLE
I have a prediciton for 50 images..but how do i map prediction to each and every result

### ISSUE THREAD

**Issue by NaveenVinayakS** [andreagemelli/doc2graph#7]

**Comment by andreagemelli** [comment]
I am providing in the next release an utility for inference on a single instance.
In the mean time either you do this yourself (take the model pertained and pass only one example per time) or, having all of them together, take the node and edge prediction all together and using number of nodes and edges per each graph as indices to correctly retrieve the prediction separately.
I close the issue.
Please provide descriptions or screenshots to leave better documentation for other users too.

**Comment by ranzmigrod** [comment]
Hi, is there a timeline on when this inference feature will be added?

**Comment by andreagemelli** [comment]
Hi @ranzmigrod,
thanks for your patience 🙌🏼 (this should turn handy also for you @NaveenVinayakS ). 
In the meantime I develop the novel feature, try this out!
In `training/funsd.py`:
- Line 177: use only one graph `gi` instead of batching them all. You can access an item either using `test_data.graphs[gi]` or `test_data[gi]`
- Line 184: `n` and `e` should be the nodes and edges predictions, respectively. If you want the `entity labelling` predictions, just use `n -> _, classes = torch.max(n, dim=1)`. 

Predictions are "one to one" with the nodes (entities) of the graph: you can access them through `your_graph.ndata['geom']` to print them on the image along with their predicted class (remember to scale them back! 🧐)

**Comment by NaveenVinayakS** [comment]
Thanks for your replay @andreagemelli
